<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [4]:
#Initialize matrix a  
a = [  
        [1, 3, 2],  
        [3, 1, 1],  
        [1, 2, 2]  
    ]
   
#Initialize matrix b  
b = [  
         [2, 1, 1],  
         [1, 0, 1],  
         [1, 3, 1]  
     ] 
   
#Calculates number of rows and columns present in first matrix  
row1 = len(a);  
col1 = len(a[0]);  
   
#Calculates number of rows and columns present in second matrix  
row2 = len(b);  
col2 = len(b[0]);  
   
#For two matrices to be multiplied,   
#number of columns in the first matrix must be equal to the number of rows in the second matrix  
  
if(col1 != row2):  
    print("Matrices cannot be multiplied");  
else:  
    #Array prod will hold the result and is initialized with zeroes.  
    prod = [[0]*row1 for i in range(col2)];  
      
    #Performs product of matrices a and b. Store the result in matrix prod  
    for i in range(0, row1):  
        for j in range(0, col2):  
            for k in range(0, row2):  
                prod[i][j] = prod[i][j] + a[i][k] * b[k][j];   
                  
    print("Product of two matrices: ");  
    for i in range(0, row1):  
        for j in range(0, col2):  
            print(prod[i][j]),  
              
        print(" ");  

Product of two matrices: 
7
7
6
 
8
6
5
 
6
7
5
 


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [14]:
import random


lst=[0, 5 ,27, 6, 13, 28, 100, 45, 10,79]   

def pick_a_number_from_list(A):
    weights1=[]
    
    for i in A:
        weights1.append(i/sum(lst))
        
    selected_random_number = random.choices(A,weights=weights1,k=1)    
    
    return selected_random_number


def sampling_based_on_magnitued():
    for i in range(1,100):
        number=pick_a_number_from_list(lst)
        print(number)
    

sampling_based_on_magnitued()


[28]
[100]
[45]
[45]
[100]
[45]
[100]
[28]
[27]
[45]
[79]
[100]
[27]
[79]
[100]
[79]
[27]
[100]
[45]
[79]
[100]
[100]
[79]
[13]
[79]
[27]
[100]
[27]
[100]
[79]
[45]
[100]
[79]
[100]
[10]
[10]
[100]
[27]
[100]
[79]
[100]
[79]
[100]
[79]
[28]
[79]
[100]
[100]
[100]
[100]
[27]
[100]
[100]
[13]
[27]
[79]
[45]
[79]
[100]
[79]
[13]
[79]
[79]
[100]
[45]
[13]
[79]
[79]
[28]
[27]
[100]
[13]
[100]
[28]
[45]
[100]
[45]
[45]
[79]
[27]
[100]
[13]
[100]
[13]
[100]
[100]
[79]
[79]
[45]
[79]
[100]
[100]
[27]
[79]
[45]
[5]
[79]
[100]
[79]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [21]:
# Using regex() + sub()
import re
  
# initializing string
test_str = '#2a$#b%c%561# '
  
# printing original string
print("The original string is : " + (test_str))
  
# initializing #
K = '#'
  
# using regex expression to solve problem 
res = re.sub(r'\d', K, test_str)
          
# printing result 
print("The resultant string : " + (res)) 

The original string is : #2a$#b%c%561# 
The resultant string : ##a$#b%c%#### 


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [71]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
# you can free to change all these codes/structure
def display_dash_board(students, marks):
    dictionary = dict(zip(Students,Marks))
    print('top_5_students')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1],reverse=True)[:5]:
          print("%s: %s" % (key, value))
    print('\nleast_5_students')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
          print("%s: %s" % (key, value))
        
    #students_within_25_and_75 = # compute this
    print('\nstudents_within_25_and_75')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1]):
      percentage = value * 100.0 / 100  # I assumed 100 as total marks 
    if 25 < percentage < 75 :
            print("%s: %s" % (key, value))

display_dash_board(Students, Marks)

top_5_students
student8: 98
student10: 80
student2: 78
student5: 48
student7: 47

least_5_students
student3: 12
student4: 14
student9: 35
student6: 43
student1: 45

students_within_25_and_75


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [24]:
import math

data = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
data.sort(key=lambda x: math.sqrt((float(x[0]) - 3) ** 2 +
                                  (float(x[1]) - (-4)) ** 2))
print(data[:5])

[(1, -1), (6, -7), (-1, -1), (6, 0), (1, 2)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [64]:
def getCor(s):
 
    first = s.split('x')
    a = float(first[0])
    
    second = first[1].split('y')
    b = float(second[0])
    c = float(second[1])
    
    return (a,b,c)


def getSide(t,p):
    
    cal = (t[0] * p[0]) + (t[1] * p[1]) + (t[2])

    if cal > 0:
        return 1
    elif cal < 0:
        return -1
    elif cal == 0:
        return 0
    return -2


def getAns(red,blue,line):
    
    sign_red = getSide(getCor(line),red[0])
    sign_blue = getSide(getCor(line),blue[0])
        
    for j in range(len(red)):
        if sign_red != getSide(getCor(line),red[j]):
            return 'no'

    for j in range(len(blue)):

        if sign_blue != getSide(getCor(line),blue[j]):
            return 'no'
    return 'Yes'


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]   
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    ans = getAns(Red, Blue, i)
    print(ans)
    
#REFERENCE--->https://stackoverflow.com/questions/57188227/to-find-whether-a-given-line-equation-is-able-to-separate-the-two-lists-of-poi

Yes
no
no
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [25]:
# takes an array x and two indices a,b. 
# Replaces all the _'s with (x[a]+x[b])/(b-a+1)
def fun(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
    # Create array from the string
    x = text.replace(" ","").split(",")
    # Get all the pairs of indices having number
    y = [i for i, v in enumerate(x) if v != '_']
    # Starting with _ ?
    if y[0] != 0:
        y = [-1] + y
    # Ending with _ ?
    if y[-1] != len(x)-1:
        y = y + [-1]    
    # run over all the pairs
    for (a, b) in zip(y[:-1], y[1:]): 
        fun(x,a,b)          
    return x

# Test cases
tests = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in tests:
    print (replace(i))
#REFERENCE----->https://stackoverflow.com/questions/57179618/filling-the-missing-values-in-the-specified-format-python/57180534

[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [33]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
from fractions import Fraction
def compute_conditional_probabilites(F,S):
    num=0
    den=0
    for i in range(len(A)):
        if(A[i][1]==S):
            den=den+1
            if(A[i][0]==F):
                num=num+1
    print('P(F={}|S=={})='.format(F,S), Fraction(num,den))

for k in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for m in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(k,m)

P(F=F1|S==S1)= 1/4
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0
P(F=F2|S==S1)= 1/4
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F3|S==S1)= 0
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3
P(F=F4|S==S1)= 1/4
P(F=F4|S==S2)= 0
P(F=F4|S==S3)= 1/3
P(F=F5|S==S1)= 1/4
P(F=F5|S==S2)= 0
P(F=F5|S==S3)= 0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [72]:
def string_features(S1, S2):
    a=[]
    b=[]
    c=[]
    for ch in S1.split():
        for ch1 in S2.split():
            if(ch ==ch1):
                a.append(ch)
    print(len(a))
    b= list(set(S1.split())-set(S2.split()))
    print(b)
    c = list(set(S2.split())-set(S1.split()))
    print(c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
print(string_features(S1, S2))

7
['5', 'F', 'first']
['S', '3', 'second']
None


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):
        sum = sum + ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    return sum 

print((compute_log_loss(A)/8)*(-1))

#REFERENCE--->Query Resolution provided by Applied AI https://classroom.appliedroots.com/v2/queryresolution/qAQy0zAg/